server:
  servlet:
    context-path: /ssm
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3310/blog?serverTimezone=UTC
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    generate-ddl: false
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package:  com.jk.model.*